[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
a = "FY7kXZMjAWJaGJYPYVPvhwSG7mXYNYJkN5WKhaVzqgrN"
counter = "ArJRUEnriCkSkGvUi1gwfi6aoBKseYjsZ7aXmraqCFq5"
sol = "7hRCCoJaLsezkJW57mGVvfcvrbmQ3cGXWX5jeePCxfyW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
