[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ammv2 = "3gFvCTqH47nAXNVYN4bNfxYCDLhUP3BBNtQisV8cZCSg"
counter = "FqYREJjB4ys9nxi3CGPxHwoRWEvcphswodYQuMoWQay3"
hello_anchor = "DhJcqp5xpc9LdpzgogLd4b9AyARP4M96j24qSACZQrjR"
my_project = "B7fXyi1xwTubKL5tyi8hEzCXvQYsUbxF6ZpfteQqfXhF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
